---
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 20:10
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
---


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)
```

```{r parts-build, include = FALSE}
library(flipbookr)
library(tidyverse)
library(gapminder)
library(animatrixr)
library(gganimate)
library(emo)

start_grid <- animatrixr::construct_grid(-8:8, -8:8) %>% 
  mutate(index = row_number(), time = 1L)

end_grid <- animatrixr::transform_segment(
    start_grid,
    m = matrix(c(0.5, 0.5, -0.5, 0.5), nrow = 2)
    ) %>%
  mutate(time = 2L)

house_points <- crossing(x = -3:3, y = -3:3) %>% 
  mutate(symbol = emo::ji("house"))

city_hall <- tibble(x = 0, y = 0)
```

```{r riddler-map, include = FALSE}
bind_rows(start_grid, end_grid) %>% 
  ggplot()+
  aes(x = x)+
  aes(y = y)+
  geom_segment(aes(xend = xend, yend = yend, group = index, colour = time))+
  geom_text(aes(label = symbol), data = house_points, size = 8)+
  geom_label(aes(label = "Riddler\nCity Hall"), data = city_hall, size = 8, color = "brown")+
  scale_colour_gradient(low = "black", high = "royalblue3")+
  scale_x_continuous(breaks = -3L:3L, minor_breaks = NULL)+
  scale_y_continuous(breaks = -3L:3L, minor_breaks = NULL)+
  coord_fixed(xlim = c(-3, 3), ylim = c(-3, 3))+
  theme_minimal()+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        legend.position = "none",
        panel.border = element_rect(colour = "black", fill=NA, size=1))
```

`r chunk_reveal("riddler-map", break_type = "auto", width_left = "49%", width_right = "50%")`

```{css, echo = FALSE}
@media print {
  .has-continuation {
    display: block;
  }
}
```