---
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 20:10
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
---


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)

library(flipbookr)
library(tidyverse)
library(gapminder)
```

```{r plot-results, include = FALSE}
gapminder %>%
  select(-c(pop, gdpPercap)) %>% 
  group_by(country, continent) %>%
  nest() %>% 
  mutate(model = map(data,
                     ~lm(lifeExp ~ year, data = .x)),
         results = map(model, broom::glance)) %>% 
  unnest(results) %>% 
  ggplot()+ 
  aes(x = continent)+
  aes(y = r.squared)+
  geom_boxplot()+
  ggbeeswarm::geom_quasirandom()+
  aes(colour = continent)+
  labs(title = "How much of life expectancy is explained by time?",
       subtitle = "For some nations (a linear pattern) does not do a good job.",
       caption = "Example from 'Many Models' chapter of 'R for Data Science'")+
  theme_bw()+
  theme(text = element_text(size = 11.5))
```

`r chunk_reveal("plot-results", break_type = "auto", width_left = "49%", width_right = "50%")`

```{css, echo = FALSE}
@media print {
  .has-continuation {
    display: block;
  }
}
```
